version: '3'

services:
  addon-dev:
    build:
      context: ../
      dockerfile: ./dockerfiles/Dockerfile.acceptance
      args:
        ADDON_NAME: '${ADDON_NAME}'
        ADDON_PATH: '${ADDON_PATH}'
        VOLTO_VERSION: ${VOLTO_VERSION:-16}
    volumes:
      - ${CURRENT_DIR}:/app/src/addons/${ADDON_PATH}/
    environment:
      RAZZLE_INTERNAL_API_PATH: http://backend-acceptance:55001/plone
      RAZZLE_API_PATH: http://localhost:55001/plone
    ports:
      - 3000:3000
      - 3001:3001
    depends_on:
      - backend-acceptance
    profiles:
      - dev

  addon-acceptance:
    build:
      context: ../
      dockerfile: ./dockerfiles/Dockerfile
      args:
        ADDON_NAME: '${ADDON_NAME}'
        ADDON_PATH: '${ADDON_PATH}'
        VOLTO_VERSION: ${VOLTO_VERSION:-16}
    volumes:
      - ${CURRENT_DIR}:/app/src/addons/${ADDON_PATH}/
    environment:
      RAZZLE_INTERNAL_API_PATH: http://backend-acceptance:55001/plone
      RAZZLE_API_PATH: http://localhost:55001/plone
    ports:
      - 3000:3000
    depends_on:
      - backend-acceptance
    profiles:
      - prod

  backend-acceptance:
    image: plone/plone-backend:${PLONE_VERSION:-6}
    command: ./bin/robot-server plone.app.robotframework.testing.VOLTO_ROBOT_TESTING
    environment:
      ZSERVER_HOST: 0.0.0.0
      ZSERVER_PORT: 55001
      # Use plone.volto rather than kitconcept.volto for the acceptance
      # testing, which makes login in tests "more conventional". - otherwise
      # it's no difference, both could make sense.
      ADDONS: 'plone.app.robotframework==2.0.0 plone.app.contenttypes plone.restapi plone.volto kitconcept.solr@git+https://github.com/kitconcept/kitconcept.solr.git@ree-add-collective-person'
      APPLY_PROFILES: plone.app.contenttypes:plone-content,plone.restapi:default,plone.volto:default-homepage,kitconcept.solr:default,collective.solr:default
      CONFIGURE_PACKAGES: plone.app.contenttypes,plone.restapi,plone.volto,plone.volto.cors,kitconcept.solr,collective.solr
      SOLR_HOST: solr-acceptance
      SOLR_PORT: 8983
      SOLR_BASE: /solr/plone
    ports:
      - 55001:55001
    profiles:
      - dev
      - prod
    depends_on:
      - solr-acceptance

  solr-acceptance:
    image: ghcr.io/kitconcept/solr:${IMAGE_TAG:-latest}
    build:
      context: ./solr
    ports:
      - 8983:8983
    volumes:
      - solr-data:/var/solr/data
    command:
      - solr-precreate
      - plone
      - /plone-config
    profiles:
      - dev
      - prod

volumes:
  solr-data: {}
