services:
  backend:
    image: plone/plone-backend:${PLONE_VERSION:-6}
    command: ./bin/robot-server plone.app.robotframework.testing.VOLTO_ROBOT_TESTING
    environment:
      ZSERVER_HOST: 0.0.0.0
      ZSERVER_PORT: 55001
      ADDONS: 'plone.app.contenttypes plone.restapi plone.volto kitconcept.solr==1.0.0a5'
      APPLY_PROFILES: plone.app.contenttypes:plone-content,plone.restapi:default,plone.volto:default-homepage,kitconcept.solr:default,collective.solr:default
      CONFIGURE_PACKAGES: plone.app.contenttypes,plone.restapi,plone.volto,plone.volto.cors,kitconcept.solr,collective.solr
      SOLR_HOST: solr
      SOLR_PORT: 8983
      SOLR_BASE: /solr/plone
    ports:
      - 55001:55001
    depends_on:
      - solr

  solr:
    image: ghcr.io/kitconcept/solr:${IMAGE_TAG:-latest}
    build:
      context: ./solr
    ports:
      - 8983:8983
    volumes:
      - solr-data:/var/solr/data
    command:
      - solr-precreate
      - plone
      - /plone-config

volumes:
  solr-data: {}
