# syntax=docker/dockerfile:1
ARG VOLTO_VERSION
FROM plone/frontend-dev:${VOLTO_VERSION}

ARG ADDON_NAME
ARG ADDON_PATH

COPY --chown=node:node package.json /app/src/addons/${ADDON_PATH}/

RUN <<EOT
    /setupAddon
    npm install -g corepack@latest
    corepack enable
    pnpm install --fetch-timeout 1000000
    pnpm build
EOT
