name: Acceptance tests
on: [push]

env:
  ADDON_NAME: '@kitconcept/volto-solr'
  ADDON_PATH: 'volto-solr'
  VOLTO_VERSION: '16'

jobs:
  acceptance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Cypress
        run: |
          cd acceptance
          yarn

      - name: 'Cypress: Acceptance tests'
        uses: cypress-io/github-action@v5
        env:
          BABEL_ENV: production
          CYPRESS_RETRIES: 2
          CURRENT_DIR: '${{ github.workspace }}'
          SOLR_CONTEXT_FOLDER: '${{ github.workspace }}/acceptance/solr'
        with:
          parallel: false
          browser: chrome
          working-directory: acceptance
          spec: cypress/tests/*.js
          install: false
          start: |
            docker compose -f docker-compose.yml --profile dev up
          wait-on:
            'npx wait-on --httpTimeout 20000 http-get://localhost:55001/plone http://localhost:3000 http://localhost:8983'

            # XXX XXX This should be working with prod!
            # docker compose -f docker-compose.yml --profile prod up
            # XXX XXX This currently works with dev.

      # Upload Cypress screenshots
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots-acceptance
          path: acceptance/cypress/screenshots

      # Upload Cypress videos
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-videos-acceptance
          path: acceptance/cypress/videos
